# Generated by Django 4.2.19 on 2025-02-22 19:29

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_profile_image_path, verbose_name='Profile Image'),
        ),
    ]
