# Generated by Django 4.2.19 on 2025-02-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('RE', 'Renewable Energy'), ('RC', 'Recycling'), ('EC', 'Emission Control')], max_length=2)),
                ('funding_goal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_raised', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('carbon_saved_per_dollar', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
