# Generated by Django 4.2.19 on 2025-02-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='carbon_saved_per_dollar',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
