# Generated by Django 4.2.19 on 2025-02-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0003_remove_initiative_carbon_saved_per_dollar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='carbon_saved',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12, verbose_name='Carbon Emissions Reduced (CO₂e Saved)'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='energy_saved_generated',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12, verbose_name='Energy Saved/Generated (kWh)'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='water_saved',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12, verbose_name='Water Conservation (Liters Saved)'),
        ),
    ]
