# Generated by Django 4.2.19 on 2025-02-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0006_initiative_status_alter_initiative_carbon_saved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='initiatives/'),
        ),
    ]
