# Generated by Django 4.2.19 on 2025-03-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0007_initiative_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='roi',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Return on Investment (ROI) in percentage.', max_digits=5),
        ),
    ]
