# Generated by Django 4.2.19 on 2025-03-02 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0009_investmentvalue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvestmentValue',
        ),
    ]
