# Generated by Django 4.2.19 on 2025-03-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0011_category_alter_initiative_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='carbon_saved',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='energy_saved_generated',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='water_saved',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
