# Generated by Django 4.2.19 on 2025-03-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0012_alter_initiative_carbon_saved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='carbon_saved',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
    ]
